imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyOrleansBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: [fr] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration

swiftmailer:
    transport: gmail
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MyOrleansBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_sender_name%"



# Services
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []

liip_imagine:

    # configure resolvers
    resolvers:
        default:
            web_path: ~

    # your filter sets are defined here
    filter_sets:
        cache: ~

        thumb_residence:
            filters:
                thumbnail:
                    size: [590, 350]
                    mode: outbound

        thumb_residence_home:
            filters:
                thumbnail:
                    size: [620, 400]
                    mode: outbound

        thumb_collaborateur:
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound

        thumb_pack:
            filters:
                thumbnail:
                    size: [395, 380]
                    mode: outbound

        thumb_article_blog:
            filters:
                thumbnail:
                    size: [615, 410]
                    mode: outbound

        thumb_article_site:
            filters:
                thumbnail:
                    size: [1000, 260]
                    mode: outbound

        thumb_articles_immopratique:
            filters:
                thumbnail:
                    size: [630, 395]
                    mode: outbound

        thumb_header_article_blog:
            filters:
                relative_resize:
                    widen: 1920

                crop:
                    size: [ 1920, 450 ]
                    start: [ 000, 300 ]


        thumb_photo_residence:
            filters:
                thumbnail:
                    size: [1200, 800]
                    mode: outband

        thumb_photo_appartement:
            filters:
                thumbnail:
                    size: [1500, 900]
                    mode: outband

        thumb_plan_appartement:
            filters:
                thumbnail:
                    size: [1500, 1060]
                    mode: outband

        thumb_images_carrousel:
            filters:
                thumbnail:
                    size: [600, 400]
                    mode: outbound

        thumb_timeline:
            filters:
                thumbnail:
                    size: [300, 150]
                    mode: outbound

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable:   true
            timestampable: true
