<?php

namespace MyOrleansBundle\Repository;

/**
 * apparteÃmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class apparteÃmentRepository extends \Doctrine\ORM\EntityRepository
{
}
