<?php

namespace MyOrleansBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function articleByTag($tag)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.')
            ->join('a.tag', 't')
            ->where('t.nom LIKE :tag')
            ->setParameter('tag', $tag);

        return $qb->getQuery()->getResult();
    }


}
