<?php

namespace MyOrleansBundle\Repository;

/**
 * CategoriePrestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePrestaRepository extends \Doctrine\ORM\EntityRepository
{
}
