<?php

namespace MyOrleansBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneEvent()
    {
        $qb = $this->createQueryBuilder('e')
            ->orderBy('e.id', 'DESC')
            ->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

    public function findAll()
    {
        $qb = $this->createQueryBuilder('e')
            ->orderBy('e.id', 'DESC')
            ->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
}
