<?php

namespace MyOrleansBundle\Repository;

/**
 * FileArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
