<?php

namespace MyOrleansBundle\Repository;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function flatsByResidenceAndStatus($residence)
    {
        $qb = $this->createQueryBuilder('f');

        $qb->where('f.residence = :residence')
            ->setParameter('residence', $residence)
            ->addOrderBy('f.statut','ASC')
            ->addOrderBy('f.surface', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
