<?php

namespace MyOrleansBundle\Repository;

/**
 * PrestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestaRepository extends \Doctrine\ORM\EntityRepository
{
}
