<?php

namespace MyOrleansBundle\Repository;

/**
 * temoignageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class temoignageRepository extends \Doctrine\ORM\EntityRepository
{
}
