<?php

namespace MyOrleansBundle\Repository;

/**
 * TypePrestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePrestaRepository extends \Doctrine\ORM\EntityRepository
{
}
