<?php

namespace MyOrleansBundle\Repository;

/**
 * TypeMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
